### ISSUE TITLE
Bootstrap 5 support?

### ISSUE THREAD

**Issue by eshimischi** [hudochenkov/postcss-sorting#100]
Hi i have project with Bootstrap 5, my config for postcss-sorting has Order and Properties-Order sections, for instance:

`order: [
    'custom-properties',
    'dollar-variables',
    {
      type: 'at-rule',
      name: 'include',
    },
    {
      type: 'at-rule',
      name: 'include',
      hasBlock: true,
    },
    'declarations',
    {
      type: 'rule',
      selector: /^&/,
    },
    {
      type: 'rule',
      selector: /^&:\w+$/,
    },
    {
      type: 'rule',
      selector: /^&::\w+$/,
    },
    {
      type: 'at-rule',
      name: 'media',
    },]`

1) transformation from SCSS to CSS with sass +
2) when i Postcss with my config it stuck and doesn't work

any specific configuration for var() - custom properties or? thanks in advanced!

**Comment by hudochenkov** [comment]
Do you still has issue?

**Comment by eshimischi** [comment]
Yes, this issue is still actual

**Comment by hudochenkov** [comment]
Could you make a repository with minimal configuration to reproduce the problem? Then I can take a look what is going on. Most likely just a configuration error.

**Comment by eshimischi** [comment]
> Could you make a repository with minimal configuration to reproduce the problem? Then I can take a look what is going on. Most likely just a configuration error.

yeah, i'll post link here a little bit later. thanks in advanced

**Comment by eshimischi** [comment]
Hi. Here is my reproduction repo https://github.com/eshimischi/postcss-sorting-bootstrap-5-issue

**Comment by eshimischi** [comment]
Seems like i've found what was not right with my configuration, has nothing to do with your plugin but postcss-preset-env

**Comment by hudochenkov** [comment]
I'll close the issue then.

**Comment by derSascha** [comment]
@eshimischi how do you get this working with bootstrap? The media queries are somehow wrong ordered and the grid system does not work anymore after sorting (see #105).
