### ISSUE TITLE
security vulnerability PostCSS

### ISSUE THREAD

**Issue by dogangok** [hudochenkov/postcss-sorting#118]
It seems like you're dealing with a security vulnerability in a dependency of your project. 
Unfortunately, there's no direct fix available for the version of PostCSS you're using. 
Would you be so kind to update the dependencies that rely on the vulnerable version of PostCSS. 
In this case update postcss@7.0.39 to postcss@8.4.32.

**Comment by hudochenkov** [comment]
This plugin on PostCSS 8 for 3 years already. Seems the issue is on your side.
