### ISSUE TITLE
adding a custom config file

### ISSUE THREAD

**Issue by sturobson** [hudochenkov/postcss-sorting#14]
Hi, I'm trying to introduce this into my clients workflow. As part of their CSS styleguide we are ordering CSS alphabetically. I see this isn't a current config option so I've made a start on one - https://gist.github.com/sturobson/aa6fad643b45891f5725d4e4f827eeeb - the question is -- how can I easly add this? I guess it's possible to drop the file into where your existing templates are but it'd be nice to be able to add your own sort order or -- when I finish this -- send a PR to include an alphabetical config? 

Thanks for this plugin.

**Comment by hudochenkov** [comment]
Hi, you can specify any sort order as `sort-order` option. For example, if you use gulp and want to store all postcss-sorting config (including sort order) in a separate JSON file, you can `require` this file and pass this object to plugin.

```js
var postcss = require('gulp-postcss');
var sorting = require('postcss-sorting');
var sortingOptions = require('./alphabetised.json');

gulp.task('css', function () {
    return gulp.src('./css/src/*.css').pipe(
        postcss([
            sorting(sortingOptions)
        ])
    ).pipe(
        gulp.dest('./css')
    );
});
```

**Comment by hudochenkov** [comment]
Is everything ok? Can I close the issue?

**Comment by danielbayley** [comment]
See also my proposed algorithm for [atom-postcss-sorting](https://github.com/lysyi3m/atom-postcss-sorting/pull/13/commits/b0f7367401c4521441ff0709a19ae28a6b02912b).
