### ISSUE TITLE
Add VS Code plugin

### ISSUE THREAD

**Issue by mrmlnc** [hudochenkov/postcss-sorting#15]
Hi, Aleks!

I created a plugin for [VS Code](https://code.visualstudio.com/) based on your package. If you want, you can add information about it in the README that repository.

Marketplace: https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-postcss-sorting
GitHub: https://github.com/mrmlnc/vscode-postcss-sorting

Best regards,
Denis Malinochkin

**Comment by hudochenkov** [comment]
Thank you! I added it 1d399ef.
