### ISSUE TITLE
Empty lines between @media rules

### ISSUE THREAD

**Issue by juwain** [hudochenkov/postcss-sorting#16]
I have such config (`…` means large array of ordered properties):
```
{
  "empty-lines-between-children-rules": 1,
  "sort-order": [
    [
      "@mixin"
    ],
    [
      …
    ],
    [
      "@media"
    ],
    [
      ">child"
    ]
  ]
}

```

This config in action:
```
.color {
  @mixin coloring;

  color: white;

  @media (--viewport-md) {
    color: green;
  }
  @media (--viewport-lg) {
    color: red;
  }

  span {
    color: black;
  }

  span {
    color: pink;
  }
}
```

Is it possible to add an empty line between `@media` constructions too, like between spans?

**Comment by hudochenkov** [comment]
Currently there is no ability to do this, but I'll add this soon.

**Comment by juwain** [comment]
Thanks, that'll be great!

**Comment by hudochenkov** [comment]
New option [`empty-lines-between-media-rules`](https://github.com/hudochenkov/postcss-sorting#empty-lines-between-media-rules) added in 1.4.0.

**Comment by juwain** [comment]
wohoo, great! 🎉

**Comment by juwain** [comment]
OK, the is an empty line between media-rules now, but there is also an additional line between media-rule and between child rule. I think there should be 1 empty line too.

```
.color {
  @mixin coloring;

  color: white;

  @media (--viewport-md) {
    color: green;
  }

  @media (--viewport-lg) {
    color: red;
  }


  span {
    color: black;
  }

  span {
    color: pink;
  }
}

```
