### ISSUE TITLE
Unknown Word Error on variable

### ISSUE THREAD

**Issue by spAnser** [hudochenkov/postcss-sorting#17]
```
<css input>:8:22: Unknown word
```
```
$color-list: 'black' 'gray' 'blue' 'white';

svg
{
    display: block;
    @each $color in $color-list
    {
        &.top-wave-#{$color}
        {
            @include wave(color($color));
        }

        &.bottom-wave-#{$color}
        {
            @include wave(color($color), down);
        }
    }
}
```

Using an atom plugin to run PostCSS but removing removing $color and leaving #{} allows it to process the file.

**Comment by hudochenkov** [comment]
Seems like it's Atom plugin problem and not postcss-sorting problem. What is your config?

**Comment by spAnser** [comment]
I used [atom-postcss-sorting](https://github.com/lysyi3m/atom-postcss-sorting) with default configuration

**Comment by hudochenkov** [comment]
Please open this issue in atom-postcss-sorting repository, because it is an issue with Atom plugin, not with postcss-sorting.
