### ISSUE TITLE
Not displaying errors when run postcss-sorting via npm

### ISSUE THREAD

**Issue by ImBrek** [hudochenkov/postcss-sorting#28]
Hi,
I'm trying run postcss-sorting via npm, all works, but if scss files have errors, npm do not display errors, hovewer run command without npm output errors to console

Command:
```
postcss --use postcss-sorting src/**/*.scss --replace
```
File with errors:
```
.test {
  padding: 1em; // ERROR HERE
}
```

**Comment by hudochenkov** [comment]
To work with SCSS files you should use [postcss-scss](https://github.com/postcss/postcss-scss) syntax so PostCSS can parse your files. Install postcss-scss syntax and then run this command:

```
postcss --use postcss-sorting --syntax postcss-scss src/**/*.scss --replace
```

**Comment by ImBrek** [comment]
Thank you. It works.
