### ISSUE TITLE
function is no good in LessCSS 

### ISSUE THREAD

**Issue by rusongyu** [hudochenkov/postcss-sorting#34]
/_before_/
.fn1(){}
.fn2(){}
.trans{
.fn1();
.fn2();
}

/_after_/
.fn1(){}
.fn2(){}
.trans{
.fn1()
.fn2()
}

The semicolon is disappear. I need it.
Another question, the function is no set postion,I hope the function is before the attitudes.

**Comment by mrmlnc** [comment]
Please, move your question to [postcss-less](https://github.com/webschik/postcss-less) repository.

**Comment by hudochenkov** [comment]
Are you sure it's not a problem with a Less parser?

**Comment by mrmlnc** [comment]
See `postcss-less v0.15`
