### ISSUE TITLE
Is it possible to add a name for config file?

### ISSUE THREAD

**Issue by lavezzi1** [hudochenkov/postcss-sorting#35]
I wonder if I can add a custom name for the config file? I hate how it looks like in the notification when I press cmd + s. I want to see something like "Successfully sorted using "My name of the team" config. Thanks.

**Comment by hudochenkov** [comment]
How do you using it? What is your setup?

**Comment by lavezzi1** [comment]
I just created a file in my root folder '.postcss-sorting.json' and wrote down my rules.

**Comment by hudochenkov** [comment]
Are you using it as a PostCSS plugin or as a plugin for an editor (which one)?

**Comment by lavezzi1** [comment]
As plugin for Atom editor.

**Comment by hudochenkov** [comment]
In this case you should create an issue in https://github.com/lysyi3m/atom-postcss-sorting repository, because current repository is for PostCSS plugin only.
