### ISSUE TITLE
Feature request: Add label to grouping config which adds a comment above the group

### ISSUE THREAD

**Issue by Aaron-Pool** [hudochenkov/postcss-sorting#38]
Example Input: 
```
.element {
    display: flex;
    border: 1px solid red;
    color: red;
    margin: 10px;
    flex: 1;
    padding: 10px;
    position: absolute;
    box-shadow: ...
}
```

Example Output:
```
.element {
    // layout styles
    display: flex;
    flex: 1;
    position: absolute;

    // structural styles
    margin: 10px;
    padding: 10px;

    // visual styles
    color: red
    border: 1px solid red;
    box-shadow: ....
}
```

This would make it substantially easier for new team members to understand why we've sorted things the way we have, which would make the style sheets more navigable in general.

**Comment by hudochenkov** [comment]
This feature has a little relevance to what plugin does. So I'm not going to add this. It can be another plugin, which consume postcss-sorting's config and add description comments.

**Comment by Aaron-Pool** [comment]
Ok! I understand the distinction. I would say that having a css sorting plugin provide a labeling mechanism for the different sections it sorts style rules into makes intuitive sense to me, but I can understand if you disagree.
