### ISSUE TITLE
Sort properties with vendor prefixes by alphabetical

### ISSUE THREAD

**Issue by morishitter** [hudochenkov/postcss-sorting#41]
I tried to fix this issue in stylefmt. https://github.com/morishitter/stylefmt/issues/175

But, declaration-block-properties-order rule of stylelint sorts properties with vendor prefixes by alphabetical order, so if it's possible, would you change its order according to stylelint one's?

**Comment by hudochenkov** [comment]
I'll do it in `2.0` because it breaks backward compatibility. Right now prefixed properties don't sort between themselves.

**Comment by hudochenkov** [comment]
`2.0` released, but prefixes don't sort alphabetically. The reasons are:

1. `declaration-block-properties-order` will be deprecated in the next major stylelint release.
2. [`stylelint-order`](https://github.com/hudochenkov/stylelint-order) will be used instead and it have no restriction on prefixes order.

I'll take a look at `stylefmt` in a few days, regarding `declaration-block-properties-order`.
