### ISSUE TITLE
Feature request: Line break in between groups of properties

### ISSUE THREAD

**Issue by jakelauer** [hudochenkov/postcss-sorting#49]
In the case of this rule: https://github.com/hudochenkov/postcss-sorting/blob/master/docs/properties-order.md#array-of-unprefixed-property-namesarray-of-group-objects

I would like an option to add a line break in between each provided group object, which would let me separate  the groups visually in the processed CSS. In this situation, the given/before/after would look like this:

Given
```
[
    {
        properties: [
            "position",
            "top"
        ]
    },
    {
        properties: [
            "display",
            "z-index"
        ]
    }
]
```

Before
```
a {
    z-index: 2;
    top: 0;
    position: absolute;
    display: block;
}
```

After

```
a {
    position: absolute;
    top: 0;
	
    display: block;
    z-index: 2;
}
```

**Comment by hudochenkov** [comment]
You can do this with `emptyLineBefore`:

```js
[
    {
        emptyLineBefore: true,
        properties: [
            "position",
            "top"
        ]
    },
    {
        emptyLineBefore: true,
        properties: [
            "display",
            "z-index"
        ]
    }
]
```
