### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by hudochenkov** [hudochenkov/postcss-sorting#5]
Is this really need?

What name to use? `$ postcss-sorting`?

**Comment by hlomzik** [comment]
I use it like `postcss -u postcss-sorting -s postcss-scss some.scss`. And it just works :)
The only disturbing thing here is the necessary prefix "postcss-".

**Comment by P233** [comment]
hi @hlomzik How do you add config in `.postcssrc.json`?  I tried to add
```
{
  "postcss-sorting": {
    "empty-lines-between-children-rules": 1,
    "empty-lines-between-media-rules": 1
  }
}
```
into `~/.postcssrc.json`. But that doesn't seem to work.

Thanks

**Comment by hudochenkov** [comment]
@P233 looks like you need to use `--config` parameter https://github.com/postcss/postcss-cli#--config-c

**Comment by P233** [comment]
Thanks, the `--config` parameter works great!
