### ISSUE TITLE
Working with SASS Syntax

### ISSUE THREAD

**Issue by Gespinha** [hudochenkov/postcss-sorting#57]
Hey there,

This package is amazing, bit it doesn't seam to be working on SASS Syntax files. Does it support SASS Syntax at all? If not, is it planned to support anytime soon?

Cheers!

**Comment by hudochenkov** [comment]
Have you tried to use it with https://github.com/aleshaoleg/postcss-sass parser?

If postcss-sorting works with this parser, then great! Otherwise fill free to contribute these support.

**Comment by Gespinha** [comment]
I've tried it now but its throwing me some errors, not sure if I'm using it right.

```
    postcss: {
      options: {
        processors: [
          require("postcss-sass")(sass, { syntax: postcssSass })
        ]
      }
    }
```

**Comment by hudochenkov** [comment]
I'm guessing you're using `grunt-postcss`. Correct config:

```js
options: {
	processors: [
		require('postcss-sorting')({ /* options */ })
	],
	syntax: require('postcss-sass'),
}
```

**Comment by Gespinha** [comment]
Great, thanks! Just tried that and it returns the following error: 

`Cannot read property 'parse' of undefined`

Any clue on how do I set this parser variable and with what value?

**Comment by hudochenkov** [comment]
Sorry, I don't know how to help :( I'm not using grunt-postcss and postcss-sass. Based on docs, it should work. Maybe `postcss-sass` author [could help](https://github.com/AleshaOleg/postcss-sass/issues/new) you configure it correctly with Grunt.

**Comment by Gespinha** [comment]
Yes, you're right. Thanks for the help with the syntax! I'll check this with the author then.

**Comment by AleshaOleg** [comment]
@hudochenkov hey, is `postcss-sorting` working with Sass syntax? If not, could we implement this feature?

**Comment by AleshaOleg** [comment]
This is not, problem of `postcss-sorting`. Can be closed, I think

**Comment by Gespinha** [comment]
If I remove postcss-sorting and run my task with this config:

      ```
  postcss: {
            options: {
              processors: [

              ],
              parser: require('postcss-sass')
            },
            dist: {
              src: '*.sass'
            }
        }
```

Its still contains the issue. Any chance postcss-sass is converting the file into something else?

**Comment by hudochenkov** [comment]
> @hudochenkov hey, is postcss-sorting working with Sass syntax? If not, could we implement this feature? It's gonna be so hard.

@AleshaOleg theoretically it should work if syntax correctly works with PostCSS.

**Comment by hudochenkov** [comment]
Closing this
