### ISSUE TITLE
Targeting custom comments on the stylesheets

### ISSUE THREAD

**Issue by Gespinha** [hudochenkov/postcss-sorting#58]
Hey,

Just a quick feature request: having a way to target custom comment patterns on the stylesheets pages would be great!

For example, if I have the following code:

```
/* ===== BUTTONS ===== */
.buttons{
   background: #000;
}
.buttons.red{
    background: #F00;
}
.buttons.blue{
    background: #00F;
}
```

I wanted to have a regex or something that allowed me to specifically target my title and configure how many spaces I wanted before and after, in order to properly organise my files.

Wouldn't this be cool?

**Comment by hudochenkov** [comment]
Yeah, it's cool. But not related to `postcss-sorting` scope. You can create your own PostCSS plugin for this thing.

**Comment by Gespinha** [comment]
It would be enhancing postcss-sorting's capabilities of sorting and organising your CSS code, don't you agree?

**Comment by hudochenkov** [comment]
I'll remove all options not related to sorting functionality (empty lines, etc.) in the next major version. Your request is out of responsibility for this tool, sorry.

**Comment by Gespinha** [comment]
Ah, ok, I understand. Are the spaces going to be added into a different plugin?

**Comment by hudochenkov** [comment]
Yes. We are working on adding autofixing functionality to [stylelint](https://stylelint.io/). Code `*-empty-line-before` rules are ready, but new stylelint version isn't released yet. Also I'll add sorting autofixing to [`stylelint-order`](https://github.com/hudochenkov/stylelint-order). So in the future you can use only one tool to lint and format your stylesheets — stylelint. I expect it will happen in summer.
