### ISSUE TITLE
Add emacs package

### ISSUE THREAD

**Issue by P233** [hudochenkov/postcss-sorting#63]
Hi Aleks,

I created an Emacs package to use the command line command (e.g. `postcss -u postcss-sorting -c ~/.postcssrc.json`) to sort the current css buffer in Emacs. 

The GitHub repo is https://github.com/P233/postcss-sorting.el
It's available on [melpa](http://melpa.org/).

Could you please consider to add it in the REAME?

All the best,
Peiwen

**Comment by hudochenkov** [comment]
Thank you for making this plugin!

Added to readme :)
