### ISSUE TITLE
Support for Jetbrains/PHP/Webstorm?

### ISSUE THREAD

**Issue by gkatsanos** [hudochenkov/postcss-sorting#69]
I just installed the POStCSS plugin for my PHPStorm but I see there's no support for the sorting plugin.

Any idea how to set it up manually?

**Comment by hudochenkov** [comment]
I don't use JetBrains products, so can't say for sure. I guess it will be similar to configuring [ESLint](https://blog.jetbrains.com/webstorm/2016/08/using-external-tools/), but you have to use [postcss-cli](https://github.com/postcss/postcss-cli) to be able run `postcss-sorting` in CLI.

**Comment by gkatsanos** [comment]
Ah yes, External tools should do it. Many thanks.

**Comment by gkatsanos** [comment]
@hudochenkov could you provide an example on how to run postcss-sorting via the cli and with an SCSS parser?

**Comment by hudochenkov** [comment]
Check https://github.com/hudochenkov/postcss-sorting#command-line Also install `postcss-scss`.

Your `postcss.config.js` might look like:

```js
module.exports = (ctx) => ({
  syntaxt: 'postcss-scss',
  plugins: {
    'postcss-sorting': {
      'order': [
        'custom-properties',
        'dollar-variables',
        'declarations',
        'at-rules',
        'rules'
      ],

      'properties-order': 'alphabetical',

      'unspecified-properties-position': 'bottom'
    }
  }
})
```

Hope it helps. I've never used this plugin via CLI.
