### ISSUE TITLE
postCSS suddenly stopped working in VSCode

### ISSUE THREAD

**Issue by baglio** [hudochenkov/postcss-sorting#70]
I'm using postCSS Sorting in VSCode from quite a lot without had a issue. I have my configuration and the shortcut correctly set; everything worked just fine.

Since yesterday, as I execute the command via the shortcut I get the warning message: _"command 'postcssSorting.sort' not found"_. Executing the command via the control panel, instead, gives me no results.

No new update where made available for VSCode, neither I've installed new extensions that could have caused this issued. I also noted that the "postcssSorting" configuration in my VSCode settings is now underlined in green, and the mouse over prompts me the message _"unknown configuration setting"_.

**Comment by mrmlnc** [comment]
Sorry, https://github.com/mrmlnc/vscode-postcss-sorting/issues/74 😩
