### ISSUE TITLE
Ability to throw error if user has broken config

### ISSUE THREAD

**Issue by mrmlnc** [hudochenkov/postcss-sorting#71]
### Links

  * https://github.com/mrmlnc/vscode-postcss-sorting/issues/74

### Description

Now error of broken config show by [`console.warn`](https://github.com/hudochenkov/postcss-sorting/blob/master/index.js#L19-L26). If I use this package inside editors (VS Code) I cannot read message of error without using debugger (not user friendly way).

### Proposal

Use `throw` or provide option for it.

**Comment by hudochenkov** [comment]
I can't replace `console.warn` with `throw` without releasing new major version. And release major with this change only isn't looks good.

Will it be enough if postcss-sorting will support new option `fail-on-incorrect-config`? (Better name idea is welcome. Will you be able to change your plugin to use this new option (i. e. add this option to user's config before running postcss-sorting from your plugin)?

**Comment by mrmlnc** [comment]
Yeap, as you want. Just want to be more friendly for users.

Maybe `strict-validate` or `throw-validate-error`.

**Comment by hudochenkov** [comment]
Thank you for your patience. `3.1.0` released. Use `{ 'throw-validate-errors': true }`.
