### ISSUE TITLE
Error when complile : Unknown word with variable interpolation ( SASS )

### ISSUE THREAD

**Issue by paallaire** [hudochenkov/postcss-sorting#75]
**Example (Gulp):** 

```
var gulp = require('gulp');
var postcss = require('gulp-postcss');
var sorting = require('postcss-sorting');

gulp.task('css', function () {
  return gulp.src('./assets/styles/_shame.scss').pipe(
    postcss([
      sorting({
        "properties-order": [
          "margin",
          "padding",
          "border",
          "background"
        ]
      })
    ])
  ).pipe(
    gulp.dest('./output')
    );
});
```

**Example (SASS) :** 

```
$loader : ".loader";

#{$loader} {
  width: 50px;
  height: 50px;
  padding: 40px;
}

```
**Error**

events.js:182
      throw er; // Unhandled 'error' event
      ^
CssSyntaxError: ...\styles\_shame.scss:15:3: Unknown word

The problem seems to come with "#{$loader}".
If on replace it with a CSS selector like ".loader"... its works

**Comment by hudochenkov** [comment]
It's because PostCSS doesn't understand SCSS by default. You [need to use](https://github.com/postcss/gulp-postcss#passing-additional-options-to-postcss) custom parser [`postcss-scss`](https://github.com/postcss/postcss-scss).

**Comment by hudochenkov** [comment]
@davidetruffo do you have [`postcss-scss`](https://github.com/postcss/postcss-scss) installed?

**Comment by davidetruffo** [comment]
@hudochenkov Yep, I did have it.

I'm using past tense here, because I then switched to stylelint (and stylelint-order). I'm already using stylelint for linting and there's not much sense in using different tools with different configs when I can accomplish everything I need with one :)
