### ISSUE TITLE
[Question]Consider adding reg type in properties-order

### ISSUE THREAD

**Issue by NE-SmallTown** [hudochenkov/postcss-sorting#77]
If do this, we can just use `/^margin/` rather than `margin`, `margin-top`, `margin-right` ....

**Comment by hudochenkov** [comment]
It won't going to happen. Explanation in related repository https://github.com/hudochenkov/stylelint-order/issues/43#issuecomment-331741788:

> There are multiple reasons we won't have wildcard support for properties:
> 
> 1. It will increase code complexity without much benefit. Config verbosity is a problem, but properties order isn't a thing, which will often be changed.
> 2. [List of all properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference) is available, and all properties could be easily copied to config.
