### ISSUE TITLE
Feature request: Non-standard CSS compatible

### ISSUE THREAD

**Issue by gucong3000** [hudochenkov/postcss-sorting#81]
If I'm not mistaken because of the limitations here, `postcss-sorting` only supports the standard CSS:
https://github.com/hudochenkov/postcss-sorting/blob/master/lib/isRuleWithNodes.js#L4

Can we support HTML like this:
```html
<a style="bottom: 15px;top: 5px;">
```

**Comment by hudochenkov** [comment]
How to overcome this limitation? What AST `postcss-styled` (or `postcss-html`) gives?

**Comment by hudochenkov** [comment]
Released in `4.1.0`. Thank you for your syntaxes!
