### ISSUE TITLE
Migration to v3 Postcss Sorting

### ISSUE THREAD

**Issue by nickngqs** [hudochenkov/postcss-sorting#82]
Is postcss sorting suppose to work together with stylelint and stylelint-order? Or is this totally two different stuff now? Currently, i'm extremely confused which to use or how to make it even work for postcss sorting v3. Everytime i tried, i'll move back to v2.

From what i understand is the order groups has been move to stylelint-order. So does autosave not work for postcss sorting in sublime? How do I make my scss file auto format in sublime?

**Comment by nickngqs** [comment]
Essentially i was using postcss-sorting to style format my scss. I have order and order groups and space in between to sort of format and beautify the spaces and order groupings. Should i go back to using v2? Im trying to find options for v2 and can't seem the locate them since they've move to v3 docs.

For example
```
.a {
  margin:50px
  font-weight: 20px;
  padding: 20px;
  font-size: 15px;
}
```

becomes

```
.a {
  margin:50px
  padding: 20px;

  font-size: 15px;
  font-weight: 20px;
}
```

**Comment by hudochenkov** [comment]
Now I understand. v3 doesn't care about empty lines, only about order. To achieve what you want you to need to setup stylelint with stylelint-order plugin. And run `stylelint --fix`. I'm not aware of packages for Sublime Text which could run `stylelint --fix` on save. I think it's possible to create a [build system](https://www.sublimetext.com/docs/3/build_systems.html) in ST, and use [SublimeOnSaveBuild](https://github.com/alexnj/SublimeOnSaveBuild) package to run this build system on save.

In your case it might be easier to stick to v2 for Sublime Text plugin, if you don't use stylelint.

P. S. If you don't use stylelint, I highly recommend to start using it. It helps [avoid](https://stylelint.io/user-guide/rules/#possible-errors) errors in CSS.

**Comment by nickngqs** [comment]
Ahh now that make sense, cause I only know of having npm run stylelint --fix on safe. I had the initial idea that postcss-sort will use stylelint internally. In the case, can you point me to your own v2 options list? 

My current issue is actually trying to place certain at rules of include seprately. How would you advise me to do that?

```
.a {
  @include grid-column(2)
  @include grid-container()
  @include media() {

  }
}
```

to a line in between for specific at rules -> in this case is @include media()
```
.a {
  @include grid-column(2)
  @include grid-container()

  @include media() {

  }
}
```

**Comment by hudochenkov** [comment]
[Here are the latest v2 docs](https://github.com/hudochenkov/postcss-sorting/tree/2.1.0). You can't enforce empty line between includes. But you can group them:

```js
{
	"order": [
		...,
		{
			type: 'at-rule',
			name: 'include',
			parameter: 'grid-column'
		},
		{
			type: 'at-rule',
			name: 'include',
			parameter: 'grid-container'
		},
		{
			type: 'at-rule',
			name: 'include',
			parameter: 'media'
		}
	]
}
```
