### ISSUE TITLE
rule sorting

### ISSUE THREAD

**Issue by akvadrako** [hudochenkov/postcss-sorting#91]
The README says that this plugin will sort rules, but when I run the example, my rules are not sorted.

Is this by design? Is there a configuration option for sorting rules alphabetically?

**Comment by hudochenkov** [comment]
Provide more information, please. How do you use it? How did you configure.

You need to enable properties sorting, because by default this plugin doesn't do anything. Option you're looking for:

```
{
     'properties-order': 'alphabetical'
}

**Comment by akvadrako** [comment]
I don't have a setup anymore; I just wrote a script to do what I needed. But I'm not interested in properties - I want to sort the rules, like the README says.

**Comment by hudochenkov** [comment]
There were might have been a misunderstanding what plugin does. It sorts what is inside rules and at-rules. It doesn't change the order for rules, which are top level rule in the file.

Anyway, looks like you don't need this plugin anymore. I'm closing this issue.
